name: CI

on:
  push:
    branches: [ master ]

env: 
  BUCKET: movidapiloto.vallorisolutions.com.br

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test --watchAll false
          
      - name: Build
        run: npm run build
        
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Upload files to bucket
        run: gsutil -m rsync -R ./build gs://${BUCKET}
  
  access: 
    runs-on: ubuntu-latest

    steps: 
      - name: Allow public access
        run: gsutil acl ch -u AllUsers:R gs://${BUCKET}
      
      - name: Set Cache-Control
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://${BUCKET}/**/*.{png,svg,css,js,tsx}
      
      
